Repository rapidsai/rapids-build-backend, pull requests merged in 2024-05, with the labels that each got.

#19 add mypy to linting checks
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  rapids_build_backend/config.py
  rapids_build_backend/impls.py
  rapids_build_backend/utils.py
Labels: improvement, non-breaking

#20 quote configuration options in error messages
  rapids_build_backend/config.py
Labels: improvement, non-breaking

#28 remove note about rapids-dependency-file-generator
  README.md
Labels: doc, non-breaking

#33 warn if dependencies file does not exist
  rapids_build_backend/impls.py
Labels: improvement, non-breaking

#35 Fix warning when dependencies.yaml doesn't exist
  rapids_build_backend/impls.py
  tests/test_impls.py
Labels: bug, non-breaking
